version: '3.12'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}    
      HOST_NAME: ${HOST_NAME}
      SERVICE: ${SERVICE}
    networks:
      - mynetwork

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${SERVICE}://${USER_NAME}:${PASSWORD}@${HOST_NAME}/${DATABASE_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    environment:
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - "8501:8501"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: