HOST_NAME = "dpg-cro1aeg8fa8c738m6sh0-a.oregon-postgres.render.com"
DATABASE_NAME = "database_glxz"
USER_NAME = "user123"
PASSWORD = "xiasxTUgTYHJcX7zWsBmniWgr68UAg1F"
DB_PORT = 5432
SERVICE = "postgresql"
